services:
  db:
    image: postgres:17
    container_name: db_globalshot
    environment:
      POSTGRES_USER: globalshotuser
      POSTGRES_PASSWORD: globalshotsecret
      POSTGRES_DB: globalshotdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U globalshotuser"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: bk_globalshot
    ports:
      - "8080:8080"
    environment:
      DB_DSN: host=db user=globalshotuser password=globalshotsecret dbname=globalshotdb port=5432 sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  pgdata: