apiVersion: v1
kind: Service
metadata:
  name: globalshot-service
  namespace: globalshot
spec:
  selector:
    app: globalshot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP