apiVersion: apps/v1
kind: Deployment
metadata:
  name: globalshotdb
  namespace: globalshot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globalshotdb
  template:
    metadata:
      labels:
        app: globalshotdb
    spec:
      containers:
        - name: globalshotdb
          image: postgres:17
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: globalshotdb-secret
          volumeMounts:
            - name: globalshotdb-pvc
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "globalshotuser", "-d", "globalshotdb"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: globalshotdb-pvc
          persistentVolumeClaim:
            claimName: globalshotdb-pvc